### ISSUE TITLE
Feat: Async API Client 

### ISSUE THREAD

**Issue by kenhktsui** [kenhktsui/anyclassifier#5]
Desc:
Llama.cpp might not be for everyone because of heavy compute in local, adding async API client results in faster speed. It can also test the performance limit of the synthetic data generation

e.g.  DeepInfra, together AI, etc

**Comment by lokwkin** [comment]
@kenhktsui please take a look at https://github.com/kenhktsui/anyclassifier/pull/9 , I have added OpenAI client and changed to asyncio queue for concurrent LLM calling
